version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.16.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm installing" # run the `echo` command
      - run: npm install
      - run: CI=true npm run build #give external environment
  test:
    docker:
      - image: cimg/node:16.16.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing stuff" # run the `echo` command
      - run: npm install
      - run: npm test 
  hithere:
    docker:
      - image: cimg/node:16.16.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "hello"
  dummy:
    docker:
      - image: cimg/node:16.16.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: echo "dummy"
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - dummy
      - test:
          requires:
            - hithere
